# Generated by Django 3.1.1 on 2020-09-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect4', '0004_auto_20200927_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameboard',
            name='all_moves',
            field=models.CharField(default='{}', max_length=1000000),
        ),
    ]
