# Generated by Django 3.1.1 on 2020-09-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect4', '0002_auto_20200927_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameboard',
            name='row1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameboard',
            name='row2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameboard',
            name='row3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameboard',
            name='row4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameboard',
            name='row5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameboard',
            name='row6',
            field=models.IntegerField(default=0),
        ),
    ]
