# Generated by Django 3.1.1 on 2020-09-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect4', '0003_auto_20200927_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameboard',
            name='all_moves',
            field=models.JSONField(default=dict),
        ),
    ]
