# Generated by Django 3.1.1 on 2020-09-27 12:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('connect4', '0003_auto_20200927_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameboard',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
