# Generated by Django 3.1.1 on 2020-09-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect4', '0005_auto_20200927_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameboard',
            name='move_num',
            field=models.IntegerField(default=0),
        ),
    ]
