# Generated by Django 3.1.1 on 2020-09-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect4', '0006_gameboard_move_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameboard',
            name='all_moves',
            field=models.JSONField(null=True),
        ),
    ]
